@startuml
title "Теплый дом" монолитное приложение диаграмма контекста

top to bottom direction

!includeurl ./C4_Component.puml

Person(user, "Пользователь", 'Пользователь системы "Теплый дом"')
Person(admin, "Специалист по обслуживанию системы", 'Сотрудник компании "Теплый дом"')

System(сontrolSystem, "Система управления отоплением", 'Система поддерживает заданную температуру в доме и включает/выключает отопление')
System(monitoringSystem, "Система мониторинга температуры", 'Система получает информацию с датчиков и отображает пользователю')

System_Ext(tempSensors, "Датчики температуры", "Получает температуру в доме пользователя")


Rel(user, сontrolSystem, "Управлять отоплением")
Rel(user, monitoringSystem, "Смотреть температуру в доме")
Rel(admin,tempSensors,"Подключает датчики к системе")
Rel(admin,сontrolSystem,"Подключает пользователя к системе")
Rel(admin,monitoringSystem,"Подключает пользователя к системе")

Rel(monitoringSystem,tempSensors,"Получает данные температуры с датчиков")
Rel(сontrolSystem,tempSensors,"Получает данные температуры с датчиков")

@enduml