@startuml
title "Теплый дом" диограмма компонента "Приложение системы управления умными устройствами"

top to bottom direction

!includeurl ./C4_Component.puml


System(ControlSystem, "Бэк-энд системы управления умным домом", "Мониторинг и управление умным домом")

Container_Boundary(ControlSystem, "ControlSystem") {
Container(IntRoutingApp, "Атентификация, авторизация, внутренняя маршрутизация", "Istio, Kubernatis", "Атентификация, авторизация, внутренняя маршрутизация систем бэк-энд")

Container(Database, "База данных ситемы", "PostgreSQL", "Хранит состояние и настройки устройств умного дома")



Container(сontrolDevApp, "Приложение системы управления умными устройствами", "Java") {

Component(сontrolInpiut, "Обработка входящих данных", 'Сортирует данные полученные на конечные точки и отправляет дальше для обработки в соответвующий компонент')
Component(сontrolAddDev, "Добавление умных устройств", 'Принимает данные с конечных точек ответчающих за взаимодействие с интерфейсом добавления умных устройств')
Component(сontrolSystem, "Управление умными устройствами", 'Формирует кманды устройствам сторонних производителей в формате зависисящем от типа устройства')
Component(monitoringSystem, "Система мониторинга текущего состояния", 'Система получает информацию о текущем состоянии умного устройства с серверов их производителей')
}
Container(MessageBroker, "Брокер сообщений", "Kafka", "Обрабатывает очередь сообщений с внешнимих ситстем")
}

System_Ext(DevSensors, "Системы управления умными устройствами сторонних производителей", "Разные внешние системы управления устройствами, интеграцию с которыми поддерживает компания")


Rel(IntRoutingApp,сontrolInpiut,"Предает информацию на контрольные точки")
Rel(IntRoutingApp,сontrolAddDev,"Предает информацию на контрольные точки связанные с добавлением новых устройств")
Rel(сontrolInpiut, сontrolSystem, "Установка нужной температуры, включение/отключение системы")
Rel(сontrolInpiut, monitoringSystem, "Получение данных о текущем состоянии устройства")
Rel(сontrolSystem, Database, "Сохранение/получение данных о состоянии системы")
Rel(monitoringSystem, Database, "Сохранение/получение данных устройств")
Rel(сontrolAddDev,Database,"Добавляет удаляет устройства из базы")
Rel(сontrolSystem,MessageBroker,"Управляет внешней системой отопления ")

Rel(MessageBroker, monitoringSystem,"Получает температуру в доме от внешней системы")
Rel(MessageBroker,DevSensors,"Получает данные с датчиков, управляет устройством")



@enduml