@startuml

title "Теплый дом"  ER диаграмма

top to bottom direction


entity "User" {
  * user_id : NUMBER
  --
  login : VARCHAR
  password : VARCHAR
  e-mail : VARCHAR
  contract_num : VARCHAR
  }

entity "House" {
  * house_id : NUMBER
  --
  user_id : NUMBER
  address : VARCHAR
  }

  entity "Device" {
  * device_id : NUMBER
  --
  device_type_id : NUMBER
  house_id : NUMBER
  serial_number : VARCHAR
  status : BOOLEAN
  }

  entity "DeviceType" {
  * device_type_id : NUMBER
  --
  device_type_info : VARCHAR
  }

  entity "Module" {
  * module_id : NUMBER
  --
  device_id: NUMBER
  module_info : VARCHAR
  }

  entity "TelemetryData" {
  * telemety_id : NUMBER
  --
  module_id : NUMBER
  send_dev_url : VARCHAR
  send_dev_data : VARCHAR
  return_dev_date : VARCHAR
  }



User ||--|{ House
House ||--|{ Device
Device }o--|| DeviceType
Device ||--|{ Module
Module ||--o{ TelemetryData

  
@enduml